Login using Token or OAuth
daniel-sc/rocketchat-modern-client pull request #14
Opened 2020-06-10 14:15 UTC by spahrson

2020-06-10 14:44 UTC, daniel-sc requested changes
Hi @spahrson,
thanks for your contribution! 
After addressing the comments (via update or answer) I'm happy to merge this!

2020-06-10 14:44 UTC, daniel-sc commented on src/main/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClient.java
>      public RocketChatClient(String url, String user, String password, Executor executor) {
Would it be cleaner to invoke the new constructor: `this(url, new LoginParam(user, password), executor)`?

2020-06-10 14:44 UTC, daniel-sc commented on src/main/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClient.java
> +    @Deprecated
Is there a specific reason for deprecating the old constructors?

2020-06-10 14:44 UTC, daniel-sc commented on src/main/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClient.java
> +    private CompletableFuture<String> loginWithToken(String token) {
Would it make sense to create a class `LoginTokenParam` analogous `LoginOAuthParam` and `LoginParam`?

2020-06-11 08:47 UTC, spahrson commented on src/main/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClient.java
>      public RocketChatClient(String url, String user, String password, Executor executor) {
> Would it be cleaner to invoke the new constructor: `this(url, new LoginParam(user, password), executor)`?

my fault. i'm going to fix this.

2020-06-11 08:50 UTC, spahrson commented on src/main/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClient.java
> +    @Deprecated
I added a new constructor taking the loginParam. So there are now two ways to achive the same. IMHO we should eliminate one of them to keep it simple and clean?

2020-06-11 09:10 UTC, spahrson commented on src/main/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClient.java
> +    private CompletableFuture<String> loginWithToken(String token) {
Changed.

2020-06-11 18:48 UTC, daniel-sc commented on src/main/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClient.java
> +    @Deprecated
If rather keep the simple additional interface. But if you still think deprecation is better, that’s fine with me, as long as you add some javadoc hinting to the new constructor.

2020-06-12 06:39 UTC, daniel-sc approved these changes
@spahrson Thanks for the updates!

2020-06-15 06:09 UTC, merged